name: Build and Release
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "export PATH=\$HOME/.deno/bin:\$PATH" >> $HOME/.bashrc
        shell: bash

      - name: Build with Deno
        run: deno run build

      - name: Create ZIP Archive
        run: zip -r release.zip /path/to/your/build/output

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
